### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException when navigating from or navigating to the QrCodeDetector's page

### ISSUE THREAD

**Issue by wpmed92** [mmaitre314/VideoEffect#13]
If I continously navigate to and navigate from the QrCodeDetector's page, the App crashes with System.Threading.Tasks.TaskCanceledException. It happens quite randomly. It's really hard to debug which task is cancelled. In my app when a barcode is decoded, it is feeded to an API and the code is translated into a Tesco product's page, where the user is navigated. So a lot of navigation from/to may occur in my app. Any idea what's wrong?

**Comment by mmaitre314** [comment]
Could that be related to the issue you hit back in February?
https://github.com/mmaitre314/VideoEffect/issues/9#issuecomment-76140688
I haven't ported that fix yet to the sample code.

Otherwise, does the exception contain any actionable callstack?

Another option to debug would be to spray try{}catch{} blocks all over the code to narrow down where the exception fires from. Intellitrace helps with tracking exceptions but I don't think that works with Phone apps.

**Comment by ahmedharmouche** [comment]
After a little more debugging it turned out that the crash is due to 'Access violation'. It isn't related to the TaskCancelledException, and actually I couldn't see any Exception at all.

**Comment by mmaitre314** [comment]
That looks like a C# debugger hitting a C++ crash. Could you try switching the debugger mode from managed to native? That might give a callstack.

**Comment by ahmedharmouche** [comment]
While debugging the native, I got some more information : "Unhandled exception at 0x64F20BA5 (WINDOWS.UI.XAML.DLL) in TescoTest.exe: 0xC0000005: Access violation reading location 0x00000003." And also gave me a callstack, you can have a look here: http://pastebin.com/S31g3mJc

**Comment by mmaitre314** [comment]
I only see XAML code there, so there is a good chance it is a XAML bug. I did some quick online search but did not find something obviously related. The best is likely to report that crash & callstack on MSDN forums.

**Comment by ahmedharmouche** [comment]
Okay Matthieu, thank you for helping me out! :) Hope I'll find the bug.
